Create the number input dialog
kuluna/ManyTime pull request #2
Opened 2020-04-20 06:09 UTC by naoyuki-matsuda

様々な数字のinput dialogとして使用できるようにNumberInputDialogFragmentを作成
overrideでformatを自由に変更できるようにしている

## 円
![device-2020-04-20-150442](https://user-images.githubusercontent.com/60590767/79719150-d8531a00-8318-11ea-894f-c75cc1bc4aa7.png)

## 分
![device-2020-04-20-150455](https://user-images.githubusercontent.com/60590767/79719155-dbe6a100-8318-11ea-8d40-29399d08aa73.png)

2020-04-20 06:28 UTC, kuluna requested changes

2020-04-20 06:28 UTC, kuluna commented on app/src/main/java/jp/kuluna/manytime/sample/MainActivity.kt
> +import kotlinx.android.synthetic.main.activity_main.*
これは...

2020-04-20 06:28 UTC, kuluna commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +    protected fun setInputValue(value: Int) {
Kotlinでsetterやgetter関数が生えることは稀です。プロパティのsetterやgetterで代用できないか試してください。

2020-04-20 06:28 UTC, kuluna commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +     * 入力値を好きなformatに変換できるようにする
これはライブラリの実装者から見た目線のコメントで、実際にはライブラリを使う人のコメントであるべきです

2020-04-20 06:28 UTC, kuluna commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
onActivityCreatedはFragment1.3.0からDeprecatedになるので今からonViewCreatedに移行をお願いします

2020-04-20 06:28 UTC, kuluna commented on app/src/main/java/jp/kuluna/manytime/sample/MainActivity.kt
> +        open_money_input_dialog.setOnClickListener {
Data BindingかView Bindingを使ってください

2020-04-20 06:29 UTC, kuluna commented
ダークテーマでどう表示されるかのスクショもお願いします

2020-04-20 06:38 UTC, naoyuki-matsuda commented on app/src/main/java/jp/kuluna/manytime/sample/MainActivity.kt
> +        open_money_input_dialog.setOnClickListener {
これも一応kotlin android extensionsのview bindingですが、kotlin android extensionsはしようしない方がいいんでしたっけ？

2020-04-20 07:25 UTC, naoyuki-matsuda commented
> ダークテーマでどう表示されるかのスクショもお願いします

現状だとダークテーマ対応してないですね。
![device-2020-04-20-162356](https://user-images.githubusercontent.com/60590767/79724986-70560100-8323-11ea-8998-22afd8bb4f45.png)

2020-04-20 07:25 UTC, naoyuki-matsuda commented on app/src/main/java/jp/kuluna/manytime/sample/MainActivity.kt
> +        open_money_input_dialog.setOnClickListener {
databindingに変えておきました！

2020-04-20 07:25 UTC, naoyuki-matsuda commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +    override fun onActivityCreated(savedInstanceState: Bundle?) {
done

2020-04-20 07:25 UTC, naoyuki-matsuda commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +     * 入力値を好きなformatに変換できるようにする
done

2020-04-20 07:26 UTC, naoyuki-matsuda commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +    protected fun setInputValue(value: Int) {
setterは削除し、initialValueはconstructorで渡すようにしました。

2020-04-20 07:26 UTC, naoyuki-matsuda commented on app/src/main/java/jp/kuluna/manytime/sample/MainActivity.kt
> +import kotlinx.android.synthetic.main.activity_main.*
databindingに変えました！

2020-04-20 07:33 UTC, kuluna commented
あっ、マテリアルComponentが1.0.0か...

2020-04-20 07:34 UTC, kuluna commented
MaterialComponentを1.1.0にしちゃいましょう

2020-04-20 07:45 UTC, naoyuki-matsuda commented
@kuluna 

こんな感じです！
![device-2020-04-20-164138](https://user-images.githubusercontent.com/60590767/79726793-51a53980-8326-11ea-92cc-ff72abf5f528.png)

2020-04-20 08:04 UTC, kuluna commented
1.1.0のWIPブランチがあるのでそれマージした後でどうなるかですね。
色がピンクのやつはSecondaryColorなので本来割り当てられてはいけない色です

2020-04-20 08:12 UTC, naoyuki-matsuda commented
> 色がピンクのやつはSecondaryColorなので本来割り当てられてはいけない色です
すみません。こちらよく理解できていないのですが、dark modeの時のprimary color, accent color
は別途用意すべきなんでしたっけ？

2020-04-20 08:15 UTC, kuluna commented
いえ1.1.0からはColorPrimary, Secondary, ColorSurfaceなど名前や役割が変わったのにColorAccentを決め打ちしているところがあるのでそれを直さないといけないという感じです

2020-04-20 09:00 UTC, naoyuki-matsuda commented
修正後
![device-2020-04-20-175707](https://user-images.githubusercontent.com/60590767/79733855-b8c7eb80-8330-11ea-9c01-f041ddb1e686.png)
![device-2020-04-20-175739](https://user-images.githubusercontent.com/60590767/79733866-bbc2dc00-8330-11ea-8561-d343031a2b5f.png)

2020-04-20 09:02 UTC, kuluna commented on app/src/main/java/jp/kuluna/manytime/sample/SampleMinutesNumberInputDialogFragment.kt
> +class SampleMinutesNumberInputDialogFragment(inputValue: Int) : NumberInputDialogFragment(inputValue) {
Fragmentに空のコンテキストがないものを作ってしまうとしんでしまいます

2020-04-20 09:26 UTC, naoyuki-matsuda commented on app/src/main/java/jp/kuluna/manytime/sample/SampleMinutesNumberInputDialogFragment.kt
> +class SampleMinutesNumberInputDialogFragment(inputValue: Int) : NumberInputDialogFragment(inputValue) {
すみません。直しました！

2020-04-20 09:59 UTC, kuluna commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +        setUpView()
oncreateViewはinflateするだけに留めてください。
ViewをinflateしたあとViewを操作するならonViewCreatedです

2020-04-20 10:00 UTC, kuluna commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +    private val maxNumberOfDigits = 10
上限桁数はopenで変更できた方が良いです

2020-04-20 10:00 UTC, kuluna commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +     * 入力値を任意のformatに変換
formatする書式を渡せばいいのかフォーマット後の文字列を返せばいいのかがわかりませんので細かくお願いします

2020-04-20 10:03 UTC, kuluna commented on manytime/src/main/java/jp/kuluna/manytime/TimeRangeView.kt
> +    private fun setTimeTextAccentColor(@ColorInt accentColor: Int) {
🤔？

2020-04-20 23:54 UTC, naoyuki-matsuda commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +        setUpView()
done

2020-04-20 23:54 UTC, naoyuki-matsuda commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +    private val maxNumberOfDigits = 10
修正しました。

2020-04-20 23:54 UTC, naoyuki-matsuda commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +     * 入力値を任意のformatに変換
done

2020-04-20 23:55 UTC, naoyuki-matsuda commented on manytime/src/main/java/jp/kuluna/manytime/TimeRangeView.kt
> +    private fun setTimeTextAccentColor(@ColorInt accentColor: Int) {
material 1. 1. 0 branchに入ってた修正？不要なら消します。

2020-04-21 00:34 UTC, naoyuki-matsuda commented
ちょっとデグレしているみたいなので、修正します。

2020-04-21 00:46 UTC, kuluna commented on manytime/src/main/java/jp/kuluna/manytime/TimeRangeView.kt
> +    private fun setTimeTextAccentColor(@ColorInt accentColor: Int) {
じゃぁ作りかけのやつですね...

2020-04-21 00:48 UTC, naoyuki-matsuda commented on manytime/src/main/java/jp/kuluna/manytime/TimeRangeView.kt
> +    private fun setTimeTextAccentColor(@ColorInt accentColor: Int) {
消しておきました。

2020-04-21 00:49 UTC, naoyuki-matsuda commented on manytime/src/main/java/jp/kuluna/manytime/NumberInputDialogFragment.kt
> +        setUpView()
DialogFragmentの場合って、onViewCreatedは呼ばれないんですね。。
onDialogCreatedにsetUpView関数などを移動しておきました。

2020-04-21 00:50 UTC, naoyuki-matsuda commented
> ちょっとデグレしているみたいなので、修正します。

直しておきました。お手隙でreviewよろしくお願いいたします！

2020-04-21 02:14 UTC, kuluna approved these changes
CASTで動かしてみましょうか〜
これは些細なことなので修正はいらないですが、サンプル用のアプリを作る時にサンプルを見る人の目線で作ってくれると嬉しいです。
例えば今サンプルアプリ開くと上にボタンが2つあるのですが、これと下に続くサンプルとの区別や意図が汲み取りにくくなっています。たぶんデバックしやすいよう一番上に置いたのでしょう。
以前はTimeRangeのサンプルとしてバリエーションがどれだけでき、さらにダイアログとして表示もできるというギャラリーだったので、見る人に対してどう見せるかというのも今後こだわっていただければと思います。

2020-04-21 02:16 UTC, merged